const state={page:"overview",data:null};
const $=s=>document.querySelector(s);
const $$=s=>[...document.querySelectorAll(s)];
const money=v=>Number(v||0).toLocaleString("vi-VN")+"đ";
const percent=v=>Number(v||0).toFixed(1)+"%";
function token(){return localStorage.getItem("dashboard_token")||$("#tokenInput").value.trim()}
function saveToken(){const v=$("#tokenInput").value.trim();if(v)localStorage.setItem("dashboard_token",v)}
async function api(path){const sep=path.includes("?")?"&":"?";const res=await fetch(`${path}${sep}token=${encodeURIComponent(token())}`);const data=await res.json().catch(()=>({}));if(!res.ok||data.ok===false)throw new Error(data.error||"Không tải được dữ liệu");return data}
function setStatus(t,ok=true){$("#connectionStatus").textContent=t;$("#connectionStatus").style.color=ok?"var(--green)":"var(--red)"}
async function loadData(){saveToken();const range=$("#rangeSelect").value;setStatus("Đang tải...");try{const data=await api(`/api/analytics?range=${range}`);state.data=data;setStatus("Đã kết nối");renderAll()}catch(e){console.error(e);setStatus(e.message,false)}}
function renderAll(){if(!state.data)return;const s=state.data.summary;$("#totalRevenue").textContent=money(s.revenue);$("#totalProfit").textContent=money(s.profit);$("#totalCost").textContent=money(s.cost);$("#marginPercent").textContent=percent(s.marginPercent);renderSeries();renderHours();renderRevenueTable();renderItemsTable();renderTablesTable();renderInventoryTable();loadExports()}
function renderSeries(){const rows=state.data.series||[];const max=Math.max(...rows.map(r=>Number(r.revenue||0)),1);$("#seriesChart").innerHTML=rows.map(r=>{const h=Math.max(5,Math.round(Number(r.revenue||0)/max*100));return `<div class="bar-item"><div class="bar ${r.profit<0?"loss":""}" style="height:${h}%"></div><b>${money(r.revenue)}</b><span>${r.label}</span></div>`}).join("")||"Chưa có dữ liệu"}
function renderHours(){const rows=state.data.hourly||[];const max=Math.max(...rows.map(r=>Number(r.revenue||0)),1);$("#hourChart").innerHTML=rows.map(r=>{const h=Math.max(5,Math.round(Number(r.revenue||0)/max*100));return `<div class="hour-item"><div class="hour-bar" style="height:${h}%"></div><span>${r.label}</span></div>`}).join("")||"Chưa có dữ liệu"}
function table(headers,rows){if(!rows.length)return"<p>Chưa có dữ liệu.</p>";return `<table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join("")}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join("")}</tr>`).join("")}</tbody></table>`}
function renderRevenueTable(){const rows=state.data.series||[];$("#revenueTable").innerHTML=table(["Kỳ","Doanh thu","Giá vốn","Lãi","Đơn","Số món"],rows.map(r=>[r.label,money(r.revenue),money(r.cost),`<span class="${r.profit>=0?"positive":"negative"}">${money(r.profit)}</span>`,r.orders,r.items]))}
function renderItemsTable(){const rows=state.data.items||[];$("#itemsTable").innerHTML=table(["Món","Danh mục","Số lượng","Doanh thu","Giá vốn","Lãi","Biên lãi"],rows.map(r=>[r.name,r.category||"-",r.quantity,money(r.revenue),money(r.cost),`<span class="${r.profit>=0?"positive":"negative"}">${money(r.profit)}</span>`,percent(r.marginPercent)]))}
function renderTablesTable(){const rows=state.data.tables||[];$("#tablesTable").innerHTML=table(["Bàn","Doanh thu","Giá vốn","Lãi","Đơn","Số món"],rows.map(r=>[r.table,money(r.revenue),money(r.cost),`<span class="${r.profit>=0?"positive":"negative"}">${money(r.profit)}</span>`,r.orders,r.items]))}
function renderInventoryTable(){const rows=state.data.inventory?.lowStock||[];$("#inventoryTable").innerHTML=table(["Tên hàng","Tồn hiện tại","Ngưỡng cảnh báo","Đơn vị"],rows.map(r=>[r.name,r.quantity,r.minQuantity,r.unit||"-"]))}
async function loadExports(){try{const data=await api("/api/exports");$("#exportsList").innerHTML=table(["Năm","File","Hạn tải","Lượt tải"],(data.items||[]).map(i=>[i.export_year,i.file_name,new Date(i.expires_at).toLocaleString("vi-VN"),i.download_count]))}catch{$("#exportsList").innerHTML="<p>Chưa có file export.</p>"}}
function switchPage(page){state.page=page;$$(".nav-btn").forEach(b=>b.classList.toggle("active",b.dataset.page===page));$$(".page").forEach(el=>el.classList.toggle("active",el.id===`page-${page}`));const titles={overview:"Dashboard thống kê",revenue:"Doanh thu & lợi nhuận",items:"Thống kê món chi tiết",tables:"Thống kê bàn",inventory:"Thống kê kho hàng",exports:"Xuất Excel năm"};$("#pageTitle").textContent=titles[page]||"Dashboard"}
function exportYear(){saveToken();const y=Number($("#yearInput").value||new Date().getFullYear());window.open(`/api/export-year?year=${y}&token=${encodeURIComponent(token())}`,"_blank");setTimeout(loadExports,1500)}
function boot(){$("#tokenInput").value=localStorage.getItem("dashboard_token")||"";$("#yearInput").value=new Date().getFullYear();$$(".nav-btn").forEach(b=>b.addEventListener("click",()=>switchPage(b.dataset.page)));$("#refreshBtn").addEventListener("click",loadData);$("#exportBtn").addEventListener("click",exportYear);$("#rangeSelect").addEventListener("change",loadData);if($("#tokenInput").value)loadData()}
boot();
