const state={page:"overview",data:null,apiBaseUrl:"",onlineConfig:null};const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];const money=v=>Number(v||0).toLocaleString("vi-VN")+"đ";const percent=v=>Number(v||0).toFixed(1)+"%";
function baseSettings(){const c=window.DASHBOARD_CONFIG||{};return{configUrl:localStorage.getItem("cg_config_url")||c.CONFIG_URL||"",token:localStorage.getItem("cg_dashboard_token")||c.DASHBOARD_TOKEN||"",refreshMs:Number(c.REFRESH_INTERVAL_MS||60000)}}function token(){return $("#tokenInput")?.value?.trim()||baseSettings().token}function cleanBase(u){return String(u||"").trim().replace(/\/$/,"")}
function setStatus(t,ok=true){$("#apiStatus").textContent=t;$("#apiStatus").style.color=ok?"var(--green)":"var(--red)"}
async function loadOnlineConfig(){const s=baseSettings();$("#configUrlInput").value=s.configUrl;$("#tokenInput").value=s.token;if(!s.configUrl||s.configUrl.includes("YOUR_GITHUB_USER")){setStatus("Chưa cấu hình CONFIG_URL",false);return null}const res=await fetch(s.configUrl+(s.configUrl.includes("?")?"&":"?")+"t="+Date.now(),{cache:"no-store"});if(!res.ok)throw new Error("Không đọc được online config");const cfg=await res.json();state.onlineConfig=cfg;state.apiBaseUrl=cleanBase(cfg.apiBaseUrl);$("#apiBaseInput").value=state.apiBaseUrl;$("#apiBaseText").textContent=state.apiBaseUrl||"Chưa có API";$("#configPreview").textContent=JSON.stringify(cfg,null,2);return cfg}
async function api(path){if(!state.apiBaseUrl)await loadOnlineConfig();if(!state.apiBaseUrl)throw new Error("Thiếu apiBaseUrl");const sep=path.includes("?")?"&":"?";const res=await fetch(`${state.apiBaseUrl}${path}${sep}token=${encodeURIComponent(token())}`,{cache:"no-store"});const data=await res.json().catch(()=>({}));if(!res.ok||data.ok===false)throw new Error(data.error||"Không tải được dữ liệu");return data}
function saveSettings(){const u=$("#configUrlInput").value.trim(),t=$("#tokenInput").value.trim();if(u)localStorage.setItem("cg_config_url",u);if(t)localStorage.setItem("cg_dashboard_token",t);loadData()}
async function loadData(){setStatus("Đang tải...");try{await loadOnlineConfig();const d=await api(`/api/dashboard-analytics?range=${$("#rangeSelect").value}`);state.data=d;setStatus("Đã kết nối");renderAll()}catch(e){console.error(e);setStatus(e.message,false)}}
function renderAll(){const s=state.data?.summary||{};$("#totalRevenue").textContent=money(s.revenue);$("#totalProfit").textContent=money(s.profit);$("#totalCost").textContent=money(s.cost);$("#marginPercent").textContent=percent(s.marginPercent);$("#totalOrders").textContent=s.totalOrders||0;$("#productsSold").textContent=s.productsSold||0;$("#customers").textContent=s.customers||0;$("#lowStockCount").textContent=s.lowStockCount||0;renderSeries();renderHours();renderRevenueTable();renderItemsTable();renderTablesTable();renderInventoryTable()}
function renderSeries(){const rows=state.data.series||[],max=Math.max(...rows.map(r=>Number(r.revenue||0)),1);$("#seriesChart").innerHTML=rows.map(r=>{const h=Math.max(5,Math.round(Number(r.revenue||0)/max*100));return `<div class="bar-item"><div class="bar ${r.profit<0?"loss":""}" style="height:${h}%"></div><b>${money(r.revenue)}</b><span>${r.label}</span></div>`}).join("")||"Chưa có dữ liệu"}
function renderHours(){const rows=state.data.hourly||[],max=Math.max(...rows.map(r=>Number(r.revenue||0)),1);$("#hourChart").innerHTML=rows.map(r=>{const h=Math.max(5,Math.round(Number(r.revenue||0)/max*100));return `<div class="hour-item"><div class="hour-bar" style="height:${h}%"></div><span>${r.label}</span></div>`}).join("")||"Chưa có dữ liệu"}
function table(h,rows){if(!rows.length)return"<p>Chưa có dữ liệu.</p>";return `<table><thead><tr>${h.map(x=>`<th>${x}</th>`).join("")}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join("")}</tr>`).join("")}</tbody></table>`}
function renderRevenueTable(){const rows=state.data.series||[];$("#revenueTable").innerHTML=table(["Kỳ","Doanh thu","Giá vốn","Lãi","Đơn","Số món"],rows.map(r=>[r.label,money(r.revenue),money(r.cost),`<span class="${r.profit>=0?"positive":"negative"}">${money(r.profit)}</span>`,r.orders,r.items]))}
function renderItemsTable(){const rows=state.data.items||[];$("#itemsTable").innerHTML=table(["Món","Danh mục","Số lượng","Doanh thu","Giá vốn","Lãi","Biên lãi"],rows.map(r=>[r.name,r.category||"-",r.quantity,money(r.revenue),money(r.cost),`<span class="${r.profit>=0?"positive":"negative"}">${money(r.profit)}</span>`,percent(r.marginPercent)]))}
function renderTablesTable(){const rows=state.data.tables||[];$("#tablesTable").innerHTML=table(["Bàn","Doanh thu","Giá vốn","Lãi","Đơn","Số món"],rows.map(r=>[r.table,money(r.revenue),money(r.cost),`<span class="${r.profit>=0?"positive":"negative"}">${money(r.profit)}</span>`,r.orders,r.items]))}
function renderInventoryTable(){const rows=state.data.inventory?.lowStock||[];$("#inventoryTable").innerHTML=table(["Tên hàng","Tồn hiện tại","Ngưỡng cảnh báo","Đơn vị"],rows.map(r=>[r.name,r.quantity,r.minQuantity,r.unit||"-"]))}
function exportCurrentExcel(){if(!state.data)return alert("Chưa có dữ liệu.");const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(state.data.series||[]),"Doanh thu");XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(state.data.items||[]),"Món");XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(state.data.tables||[]),"Bàn");XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(state.data.inventory?.lowStock||[]),"Kho");XLSX.writeFile(wb,`cg-dashboard-${new Date().toISOString().slice(0,10)}.xlsx`)}
function switchPage(p){state.page=p;$$(".nav-btn").forEach(b=>b.classList.toggle("active",b.dataset.page===p));$$(".page").forEach(e=>e.classList.toggle("active",e.id===`page-${p}`));const titles={overview:"Dashboard thống kê",revenue:"Doanh thu & lợi nhuận",items:"Thống kê món chi tiết",tables:"Thống kê bàn",inventory:"Thống kê kho hàng",exports:"Xuất Excel",settings:"Kết nối API"};$("#pageTitle").textContent=titles[p]||"Dashboard"}
function boot(){$("#yearInput").value=new Date().getFullYear();$$(".nav-btn").forEach(b=>b.addEventListener("click",()=>switchPage(b.dataset.page)));$("#refreshBtn").addEventListener("click",loadData);$("#saveSettingsBtn").addEventListener("click",saveSettings);$("#exportCurrentBtn").addEventListener("click",exportCurrentExcel);$("#rangeSelect").addEventListener("change",loadData);loadData();setInterval(loadData,baseSettings().refreshMs)}boot();
